version: "3"

services:
    db:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}

    web:
      build: .
      command: bash -c "python3 manage.py migrate && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
      container_name: "django-web"
      working_dir: /app/src
      volumes:
      - .:/src
      ports: 
      - "8000:8000"
      depends_on:
      - db
      env_file:
        - ./src/app/.env
