version: "3"

services:
  db:
    image: postgres
    container_name: 'postgres'
    hostname: db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  web:
    build: .
    command: bash -c 'python3 manage.py migrate && gunicorn app.wsgi:application --bind 0.0.0.0:8000'
    container_name: 'django-web'
    working_dir: /app/src
    volumes:
      - .:/src
    expose:
      - 8000
    depends_on:
      - db
      - redis
    env_file:
      - ./src/app/.env

  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    hostname: redis

  celery:
    restart: always
    build: .
    container_name: 'celery'
    command: celery -A app worker -B -E -l INFO
    working_dir: /app/src
    volumes:
      - .:/src
    depends_on:
      - web
      - redis
      - db

  nginx:
    build: ./nginx
    container_name: 'nginx'
    ports:
      - 8000:80
    depends_on:
      - web
