# Generated by Django 3.2 on 2021-04-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='eggs.jpg', upload_to=''),
        ),
    ]
