# Generated by Django 3.2 on 2021-04-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='cpu.jpg', upload_to=''),
        ),
    ]
