# Generated by Django 3.2 on 2021-05-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210506_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_data',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='relesed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorit_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
