# Generated by Django 3.2 on 2021-05-11 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210511_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 11, 15, 52, 34, 904758)),
        ),
    ]
