# Generated by Django 3.2 on 2021-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_release_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
