# Generated by Django 3.2 on 2021-05-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_release_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='release_data',
        ),
    ]
