# Generated by Django 3.2 on 2021-05-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_release_data_product_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='relesed',
            new_name='released',
        ),
    ]
